---
- name: AIDE
  hosts: webservers
  sudo: yes
  tasks:
  
    - name: Install AIDE
      yum: name=aide state=present
  
    - name: Create AIDE configuration file
      template: src=templates/aide.conf.j2 dest=/etc/aide.conf
      
    - name: Lock AIDE configuration file
      command: chattr +i /etc/aide.confll
      
    - name: Initialize AIDE database in node
      command: aide -i
      
    - name: Retrieve AIDE database from node
      fetch: src=/var/lib/aide/{{ansible_nodename}}-aide.new.db.gz dest=/opt/cloudhost/aide-files/ fail_on_missing=yes
      
    - name: Delete AIDE database from node
      command: rm -f /var/lib/aide/{{ansible_nodename}}-aide.new.db.gz